spring:
  application:
    name: hse-distributed-software-systems
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dss}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}

    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

    task:
      execution:
        pool:
          core-size: 5
          max-size: 20

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql: TRACE

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

generator:
  service:
    url: ${GENERATOR_SERVICE_URL:http://localhost:8082}
export:
  service:
    url: ${EXPORT_SERVICE_URL:http://localhost:8083}

