#version: '3.8'
#services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
#    container_name: elasticsearch
#    environment:
#      - node.name=es01
#      - cluster.name=docker-cluster
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    networks:
#      - backend_net
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.7.0
#    container_name: logstash
#    volumes:
##      - ./logstash/config:/usr/share/logstash/config
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "5000:5000"
#    depends_on:
#      - elasticsearch
#    networks:
#      - backend_net
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.7.0
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#    networks:
#      - backend_net
#
#volumes:
#  esdata:
#    driver: local
#
#networks:
#  backend_net:
#    name: backend_net
#    driver: bridge
#
