spring:
  application:
    name: hse-distributed-software-systems
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/dss
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml

    task:
      execution:
        pool:
          core-size: 5
          max-size: 20

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type.descriptor.sql: TRACE

server:
  port: 8080


